tom32i_showcase:
  path: "%kernel.project_dir%/var/games"
  cache: "%kernel.project_dir%/var/cache/games"
  presets:
    large: { w: 1920, h: 1080, dpr: 1, fit: crop }
    #largeX2: { w: 1920, h: 1080, dpr: 2, fit: crop }
    medium: { w: 1280, h: 720, dpr: 1, fit: crop }
    mediumX2: { w: 1280, h: 720, dpr: 2, fit: crop }
    small: { w: 960, h: 540, dpr: 1, fit: crop }
    smallX2: { w: 960, h: 540, dpr: 2, fit: crop }
    mobile: { w: 656, h: 369, dpr: 1, fit: crop }
    mobileX2: { w: 656, h: 369, dpr: 2, fit: crop }
    largeWP: { w: 1920, h: 1080, dpr: 1, fit: crop, fm: webp }
    #largeX2WP: { w: 1920, h: 1080, dpr: 2, fit: crop, fm: webp }
    mediumWP: { w: 1280, h: 720, dpr: 1, fit: crop, fm: webp }
    mediumX2WP: { w: 1280, h: 720, dpr: 2, fit: crop, fm: webp }
    smallWP: { w: 960, h: 540, dpr: 1, fit: crop, fm: webp }
    smallX2WP: { w: 960, h: 540, dpr: 2, fit: crop, fm: webp }
    mobileWP: { w: 656, h: 369, dpr: 1, fit: crop, fm: webp }
    mobileX2WP: { w: 656, h: 369, dpr: 2, fit: crop, fm: webp }
