tom32i_showcase:
  path: "%kernel.project_dir%/games"
  cache: "%kernel.project_dir%/var/cache/games"
  group_class: App\Model\Game
  image_class: App\Model\Screenshot
  presets:
    # Large
    large: { w: 1920, h: 1080, dpr: 1, fit: crop }
    #largeX2: { w: 1920, h: 1080, dpr: 2, fit: crop }
    #largeWP: { w: 1920, h: 1080, dpr: 1, fit: crop, fm: webp }
    #largeX2WP: { w: 1920, h: 1080, dpr: 2, fit: crop, fm: webp }

    # Medium
    medium: { w: 1280, h: 720, dpr: 1, fit: crop }
    mediumX2: { w: 1280, h: 720, dpr: 2, fit: crop }
    #mediumWP: { w: 1280, h: 720, dpr: 1, fit: crop, fm: webp }
    #mediumX2WP: { w: 1280, h: 720, dpr: 2, fit: crop, fm: webp }

    # Small
    small: { w: 960, h: 540, dpr: 1, fit: crop }
    smallX2: { w: 960, h: 540, dpr: 2, fit: crop }
    #smallWP: { w: 960, h: 540, dpr: 1, fit: crop, fm: webp }
    #smallX2WP: { w: 960, h: 540, dpr: 2, fit: crop, fm: webp }

    # Mobile
    mobile: { w: 656, h: 369, dpr: 1, fit: crop }
    mobileWP: { w: 656, h: 369, dpr: 1, fit: crop, fm: webp }
    mobileX2WP: { w: 656, h: 369, dpr: 2, fit: crop, fm: webp }
    mobileX2: { w: 656, h: 369, dpr: 2, fit: crop }
