twig:
    file_name_pattern: '*.twig'
    form_themes: ['form/theme.html.twig']
    date:
        timezone: "Europe/Paris"
    globals:
        umami_id: "%env(APP_UMAMI_ID)%"

when@test:
    twig:
        strict_variables: true
