when@dev:
    web_profiler:
        toolbar: "%kernel.debug%"
        intercept_redirects: "%kernel.debug%"

    framework:
        profiler:
            collect_serializer_data: "%kernel.debug%"

when@test:
    framework:
        profiler: { collect: false }
