when@dev:
    web_profiler:
        toolbar: "%kernel.debug%"
        intercept_redirects: "%kernel.debug%"

    framework:
        profiler:
            collect: "%kernel.debug%"
            only_exceptions: false
            collect_serializer_data: "%kernel.debug%"

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler: { collect: false }
