####################################################################
# !!! REMINDER !!!                                                 #
# Don't forget to run `manala up` each time you update this file ! #
####################################################################

manala:
    recipe: elao.app

##########
# System #
##########

system:
    version: 9
    hostname: gameoscope.vm
    php:
        version: 7.4
        extensions:
          # Symfony
          - intl
          - curl
          - mbstring
          - xml
    symfony:
        version: '*'
    nodejs:
        version: 12

    ssh:
        config: |
            Host tom32i.fr
                User         tom32i
                ForwardAgent yes
            Host deployer.vm
                User         tom32i
                ForwardAgent yes

############
# Releases #
############

releases:
  - &release
    #app: api
    mode: production
    #repo: git@github.com:Tom32i/release-gameoscope.git
    repo: git@git.deployer.vm:/home/git/release/gameoscope.git
    # Release
    release_tasks:
      - shell: make install@production
      - shell: composer dump-env --empty prod
      - shell: make build@production
    release_add:
      - .env.local.php
      - bin
      - composer.*
      - config
      - Makefile
      - node_modules
      - public
      - src
      - templates
      - translations
      - vendor
    # Deploy
    deploy_hosts:
      - ssh_host: tom32i.fr
    deploy_dir: /home/tom32i/gameoscope
    deploy_shared_dirs:
      - var/log
      - var/sessions
      - var/games
      - var/cache/games
    deploy_shared_files:
      - .env.local.php
    deploy_tasks:
      - shell: make warmup@production
    deploy_post_tasks:
      - shell: sudo /bin/systemctl reload php7.4-fpm

  - <<: *release
    mode: staging
    # Release
    release_tasks:
      - shell: make install@staging
      - shell: composer dump-env --empty prod
      - shell: make build@staging
    # Deploy
    deploy_hosts:
      - ssh_host: deployer.vm
    deploy_tasks:
      - shell: make warmup@staging
