all:
    children:

        production:
            hosts:
                localhost@production:
                    ansible_connection: local
            vars:
                release_dir: /srv/release/production
                release_git_dir: /srv/app
                release_repo: git@tom32i.fr:/home/git/release/gameoscope.git
                release_version: production
                release_tasks:
                  - shell: make install@production
                  - shell: composer dump-env --empty prod
                  - shell: make build@production
                release_add:
                  - .env.local.php
                  - bin
                  - composer.*
                  - config
                  - Makefile
                  - public
                  - src
                  - templates
                  - translations
                  - vendor

        staging:
            hosts:
                localhost@staging:
                    ansible_connection: local
            vars:
                release_dir: /srv/release/staging
                release_git_dir: /srv/app
                release_repo: git@tom32i.fr:/home/git/release/gameoscope.git
                release_version: staging
                release_tasks:
                  - shell: make install@staging
                  - shell: composer dump-env --empty prod
                  - shell: make build@staging
                release_add:
                  - .env.local.php
                  - bin
                  - composer.*
                  - config
                  - Makefile
                  - public
                  - src
                  - templates
                  - translations
                  - vendor
